---
- name: RabbitMQ Cluster Configuration 
  hosts: rabbitmq_cluster
  become: true
  roles:
  - rabbitmq

- name: HAProxy Configuration
  hosts: rabbitmq_haproxy
  become: true
  roles: haproxy
...

# All made in CentOS 7