---
- name: Add EPEL repository
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Add Erlang repository
  ansible.builtin.yum:
    name: http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    state: present

- name: Install Erlang
  ansible.builtin.yum:
    name: erlang
    state: present

- name: Install RabbitMQ Server
  ansible.builtin.yum:
    name: rabbitmq-server
    state: present

- name: Create empty list for /etc/hosts
  ansible.builtin.set_fact:
    host_entries: []

- name: Fill host_entries
  ansible.builtin.set_fact:
    host_entries: "{{ host_entries + [hostvars[item]['ansible_default_ipv4']['address'] + ' ' + item]}}"
  loop: "{{ groups['rabbitmq_cluster'] }}"
  when: "'rabbitmq_cluster' in group_names"

- name: Add IP-lines to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  loop: "{{ host_entries }}"
  when: "'rabbitmq_cluster' in group_names"

- name: Get cookie from main machine
  ansible.builtin.slurp:
    src: /var/lib/rabbitmq/.erlang.cookie
  register: rabbitmq_main_cookie
  when: "main_server is defined and main_server == true"

- name: Copy cookie for slave servers
  ansible.builtin.copy:
    content: |
      {{ rabbitmq_main_cookie }}
    dest: /var/lib/rabbitmq/.erlang.cookie
  when: "main_server is defined and main_server == false"

- name: Enable and start RabbitMQ Server
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Get info from RabbitMQ cluster status
  ansible.builtin.shell: rabbitmqctl cluster_status
  register: cluster_status

- ansible.builtin.debug:
    msg: cluster_status
  tags: rabbitmq_status